name: Main devops pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  ci-pipeline:
    # here we import our lacl template
    # security tips: we set authorization to this job
    permissions:
      id-token: write
      contents: read

    uses: ./.github/workflows/node-ci-template.yml
    with:
      image-name: "875691018539.dkr.ecr.eu-central-1.amazonaws.com/secure-demo-api"
      node-version: "24.x"
