name: Main devops pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  ci-pipeline:
    # here we import our lacl template
    # security tips: we set authorization to this job
    permissions:
      id-token: write
      contents: read

    uses: ./.github/workflows/node-ci-template.yaml
    with:
      image-name: "://amazonaws.com"
      node-version: "20.x"
